name: Build (main)

on:
  push:
    branches: [main]

jobs:
  build:
    container:
      image: texlive/texlive@sha256:4e514fb5596a8db3defd38f40fc0f7b119eb3fcc88a4bfe291cd36eb00551ddb
    runs-on: self-hosted
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Make resume (PDF)
        run: make build-resume
      - name: Make SOP (PDF)
        run: make build-sop
      - uses: actions/upload-artifact@v3
        with:
          name: resume-and-sop-${{ github.ref_name }}-${{ github.sha }}
          path: |
            resume.pdf
            sop.pdf
