name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: texlive/texlive

    steps:
    - uses: actions/checkout@v2
    
    - name: Make PDF
      run: make build
