name: Check & Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    container:
      image: texlive/texlive:latest
    runs-on: self-hosted
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Check style
        run: make check-pretty
  build:
    needs: [check]
    container:
      image: texlive/texlive:latest
    runs-on: self-hosted
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Make PDF
        run: make build
      - uses: actions/upload-artifact@v2
        with:
          path: resume.pdf
