name: Check & Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    container:
      image: texlive/texlive:latest
    runs-on: self-hosted
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Check style
        run: make check-pretty
  check-version:
    container:
      image: debian:stable
    runs-on: self-hosted
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          path: current
      - name: Check out main
        uses: actions/checkout@v2
        with:
          ref: main
          path: main
      - name: Compare
        run: >-
          [[ $(cut -f1 -d" " main/version.dat) < $(cut -f1 -d" " current/version.dat) ]]
        shell: bash
  build:
    needs: [check]
    container:
      image: texlive/texlive:latest
    runs-on: self-hosted
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Make PDF
        run: make build
      - uses: actions/upload-artifact@v2
        with:
          name: resume
          path: resume.pdf
